# Site settings
title: BlueAccords
email: myoldemailname@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Just a developer and their nice blog
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
twitter_username: BlueAccords
github_username:  BlueAccords
linkedin_url: ryan-tran-85013b83
# Build settings
markdown: kramdown

highlighter: pygments

# Pagination
gems: [jekyll-paginate]
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  # poetry:
  #   output: true
  #   permalink: /poetry/:path/
